### ISSUE TITLE
Cannot use free trial

### ISSUE THREAD

**Issue by jtiee** [ElytraApp/Elytra#1]
When I get to the Subscription page, I see:

<img width="792" alt="Screenshot 2023-08-11 at 4 16 20 PM" src="https://github.com/ElytraApp/Elytra/assets/126189968/6787d80f-2ea6-4ff0-b063-9c34d46d82eb">

There is no obvious way to use the app without purchasing a subscription.

Clicking Restore prompts me to authenticate my Apple ID, but then does nothing.

Clicking Cancel Subscription produces an Error Refunding Purchase dialog.

I do not want to click Buy, since I want to try the app first.

When I use the File > New Window option, a new window asks me to sign in with Apple, and the process starts again.

Additionally, each new window I've opened cannot be closed. When I reach the subscription page, there is an X button in the top right, but clicking that closes the window and opens a new window at the beginning of the setup process.

I have been able to use the File > New Feed option to add feeds, but I cannot see those feeds since the Go > Unread, Go > Today, and Go > Bookmarks options are greyed out.

If there is no way to use the app without buying a subscription, that's fine, but do not advertise a free trial if it is not possible to use the app for free.

**Comment by dezinezync** [comment]
Hi @jtiee, sorry for the delayed response. 

It's an unfortunate situation for indie-developers who have to setup paywalls like this for free trials. 

The free 14-day trial is a part of the subscription. That's the only way we can get approval for the review process. Other mechanisms (like a real free trail), unfortunately, do not always pass review.

**Comment by jtiee** [comment]
I get that factors beyond your control could be forcing your hand. But it is still incumbent on you to explain the situation accurately. Even a simple "A subscription is required to try Elytra" would be helpful. I would not have started the subscription to try Elytra, but I'd know that the situation was intentional and not a bug.
